spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      datasource:
        flow:
          server-addr: 127.0.0.1:8848
          dataId: cloudalibaba-sentinel-service
          groupId: DEFAULT_GROUP
          dataType: json
          ruleType: FLOW
